### ISSUE TITLE
import assert {type: "json"} causes error in Safari & Firefox

### ISSUE THREAD

**Issue by t-vanasseldonk** [t-vanasseldonk/t-vanasseldonk.github.io#1]
main.js:1: import contractData from '/contracts/Manifest.json' assert { type: "json" };

This line causes an error in Safari & Firefox, causing the rest of the JS file not to load

**Comment by cxkoda** [comment]
Oh sorry, I didn't really test it properly yesterday evening. But that's something that should be resolved quite easily.On 22 Jan 2022 13:08, t-vanasseldonk ***@***.***> wrote:
main.js:1: import contractData from '/contracts/Manifest.json' assert { type: "json" };
This line causes an error in Safari & Firefox, causing the rest of the JS file not to load

**Comment by cxkoda** [comment]
I'll take a look later tonight :)On 22 Jan 2022 14:51, David Huber ***@***.***> wrote:Oh sorry, I didn't really test it properly yesterday evening. But that's something that should be resolved quite easily.On 22 Jan 2022 13:08, t-vanasseldonk ***@***.***> wrote:
main.js:1: import contractData from '/contracts/Manifest.json' assert { type: "json" };
This line causes an error in Safari & Firefox, causing the rest of the JS file not to load

**Comment by cxkoda** [comment]
I just pushed a fix for the import issue. When you have time, could you please make sure that the solution works also on your devices?
Disclaimer: I'm not really well versed in frontend-tech (as you may have noticed). So please double-check every code that I add here.
